//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntellIDE_PRUEBA02
    {
        public string ContentTypeId { get; set; }
        public string Title { get; set; }
        public string C_ModerationComments { get; set; }
        public string File_x0020_Type { get; set; }
        public string IntellideUsuario { get; set; }
        public string f_Nombre { get; set; }
        public string f_Apellido { get; set; }
        public string f_Materno { get; set; }
        public string f_Email { get; set; }
        public string f_RFC { get; set; }
        public string f_CURP { get; set; }
        public string f_FechaNacimiento { get; set; }
        public string f_LugarNacimiento { get; set; }
        public string f_Nacionalidad { get; set; }
        public string f_Escolaridad { get; set; }
        public string f_TelefonoParticular { get; set; }
        public string f_TelefonoOficina { get; set; }
        public string f_TelefonoCelular { get; set; }
        public string f_Calle { get; set; }
        public string f_NoExterior { get; set; }
        public string f_NoInterior { get; set; }
        public string f_CP { get; set; }
        public string f_Colonia { get; set; }
        public string f_Poblacion { get; set; }
        public string f_Estado { get; set; }
        public string f_Calle2 { get; set; }
        public string f_NoExterior2 { get; set; }
        public string f_NoInterior2 { get; set; }
        public string f_CP2 { get; set; }
        public string f_Colonia2 { get; set; }
        public string f_Poblacion2 { get; set; }
        public string f_Estado2 { get; set; }
        public string f_Instituciones { get; set; }
        public string Author { get; set; }
        public string Editor { get; set; }
        public string Modified { get; set; }
        public string Created { get; set; }
        public string ID { get; set; }
        public string ContentType { get; set; }
        public string C_HasCopyDestinations { get; set; }
        public string C_CopySource { get; set; }
        public string owshiddenversion { get; set; }
        public string WorkflowVersion { get; set; }
        public string C_UIVersion { get; set; }
        public string C_UIVersionString { get; set; }
        public string Attachments { get; set; }
        public string C_ModerationStatus { get; set; }
        public string Edit { get; set; }
        public string LinkTitleNoMenu { get; set; }
        public string LinkTitle { get; set; }
        public string LinkTitle2 { get; set; }
        public string SelectTitle { get; set; }
        public string InstanceID { get; set; }
        public string Order { get; set; }
        public string GUID { get; set; }
        public string WorkflowInstanceID { get; set; }
        public string FileRef { get; set; }
        public string FileDirRef { get; set; }
        public string Last_x0020_Modified { get; set; }
        public string Created_x0020_Date { get; set; }
        public string FSObjType { get; set; }
        public string SortBehavior { get; set; }
        public string PermMask { get; set; }
        public string FileLeafRef { get; set; }
        public string UniqueId { get; set; }
        public string SyncClientId { get; set; }
        public string ProgId { get; set; }
        public string ScopeId { get; set; }
        public string HTML_x0020_File_x0020_Type { get; set; }
        public string C_EditMenuTableStart { get; set; }
        public string C_EditMenuTableStart2 { get; set; }
        public string C_EditMenuTableEnd { get; set; }
        public string LinkFilenameNoMenu { get; set; }
        public string LinkFilename { get; set; }
        public string LinkFilename2 { get; set; }
        public string DocIcon { get; set; }
        public string ServerUrl { get; set; }
        public string EncodedAbsUrl { get; set; }
        public string BaseName { get; set; }
        public string MetaInfo { get; set; }
        public string C_Level { get; set; }
        public string C_IsCurrentVersion { get; set; }
        public string ItemChildCount { get; set; }
        public string FolderChildCount { get; set; }
        public string IntellIDE_GUID { get; set; }
        public Nullable<long> IntellIDE_Owner { get; set; }
        public Nullable<int> IntellIDE_Status { get; set; }
        public Nullable<System.DateTime> IntellIDE_CreatedDate { get; set; }
        public Nullable<System.DateTime> IntellIDE_ModifyDate { get; set; }
        public long IntellIDE_PK_PRUEBA02 { get; set; }
        public string IntellIDE_Folio { get; set; }
    }
}
