//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLASIFICACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CLASIFICACION()
        {
            this.TB_TRAMITES_TB_CLASIFICACION = new HashSet<TB_TRAMITES_TB_CLASIFICACION>();
            this.TB_TRAMITES_TB_CLASIFICACION1 = new HashSet<TB_TRAMITES_TB_CLASIFICACION>();
        }
    
        public long PK_CLASIFICACION { get; set; }
        public string FL_NAME { get; set; }
        public string FL_GUID { get; set; }
        public Nullable<int> FL_ORDEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TRAMITES_TB_CLASIFICACION> TB_TRAMITES_TB_CLASIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TRAMITES_TB_CLASIFICACION> TB_TRAMITES_TB_CLASIFICACION1 { get; set; }
    }
}
