//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DIRECCIONES
    {
        public long PK_DIRECCION { get; set; }
        public Nullable<int> FL_TIPO { get; set; }
        public string FL_CALLE { get; set; }
        public string FL_NUMERO_I { get; set; }
        public string FL_NUMERO_E { get; set; }
        public string FL_COLONIA { get; set; }
        public string FL_POBLACION { get; set; }
        public string FL_ESTADO { get; set; }
        public string FL_CP { get; set; }
        public string FL_TELEFONO { get; set; }
        public Nullable<long> FK_USER { get; set; }
        public Nullable<bool> FL_ACTIVO { get; set; }
    
        public virtual TB_USERS TB_USERS { get; set; }
    }
}
