//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOG
    {
        public long PK_LOG { get; set; }
        public string FL_ACTIVIDAD { get; set; }
        public Nullable<long> FK_USER { get; set; }
        public Nullable<int> FL_TIPO { get; set; }
        public Nullable<System.DateTime> FL_FECHA { get; set; }
        public Nullable<long> FK_ACTIVIDAD { get; set; }
    
        public virtual TB_ACTIVIDADES TB_ACTIVIDADES { get; set; }
        public virtual TB_USERS TB_USERS { get; set; }
    }
}
