//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MISDOCUMENTOS
    {
        public long PK_MISDOCUMENTOS { get; set; }
        public Nullable<long> FK_USER { get; set; }
        public Nullable<long> FK_TIPO_DOCUMENTO { get; set; }
        public byte[] FL_ARCHIVO { get; set; }
        public string FL_MIME { get; set; }
        public Nullable<long> FK_TRAMITE { get; set; }
        public string FL_SOLICITUD { get; set; }
        public Nullable<bool> FL_ACTIVO { get; set; }
    
        public virtual TB_TIPO_DOCUMENTOS TB_TIPO_DOCUMENTOS { get; set; }
        public virtual TB_TRAMITES TB_TRAMITES { get; set; }
        public virtual TB_USERS TB_USERS { get; set; }
    }
}
