//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OFICINAS
    {
        public long PK_OFICINA { get; set; }
        public string FL_NAME { get; set; }
        public string FL_DIRECCION { get; set; }
        public string FL_EMAIL { get; set; }
        public string FL_TELEFONO { get; set; }
        public string FL_HORA_MI { get; set; }
        public string FL_HORA_MF { get; set; }
        public string FL_HORA_VI { get; set; }
        public string FL_HORA_VF { get; set; }
        public Nullable<int> FL_ESTATUS { get; set; }
        public string FL_DIAS_INHABILES { get; set; }
        public string FL_GUID { get; set; }
        public string FL_URL { get; set; }
        public string FL_ZONA { get; set; }
    }
}
