//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO_DOCUMENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TIPO_DOCUMENTOS()
        {
            this.TB_DOCUMENTOS_TRAMITES = new HashSet<TB_DOCUMENTOS_TRAMITES>();
            this.TB_MISDOCUMENTOS = new HashSet<TB_MISDOCUMENTOS>();
        }
    
        public long PK_TIPO_DOCUMENTO { get; set; }
        public string FL_NOMBRE { get; set; }
        public string FL_GUID { get; set; }
        public Nullable<int> FL_CADUCIDAD { get; set; }
        public Nullable<bool> FL_CONSERVA { get; set; }
        public string FL_TIPO { get; set; }
        public Nullable<bool> FL_AGREGADO { get; set; }
        public Nullable<bool> FL_MIS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DOCUMENTOS_TRAMITES> TB_DOCUMENTOS_TRAMITES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MISDOCUMENTOS> TB_MISDOCUMENTOS { get; set; }
    }
}
