//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TRAMITES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TRAMITES()
        {
            this.TB_DOCUMENTOS = new HashSet<TB_DOCUMENTOS>();
            this.TB_DOCUMENTOS_TRAMITES = new HashSet<TB_DOCUMENTOS_TRAMITES>();
            this.TB_MISDOCUMENTOS = new HashSet<TB_MISDOCUMENTOS>();
            this.TB_TRAMITES_TB_CLASIFICACION = new HashSet<TB_TRAMITES_TB_CLASIFICACION>();
        }
    
        public long PK_TRAMITE { get; set; }
        public string FL_NAME { get; set; }
        public string FL_DESCRIPCION { get; set; }
        public Nullable<long> FK_TIPO_TRAMITE { get; set; }
        public Nullable<int> FL_AUTENTIFICACION { get; set; }
        public Nullable<bool> FL_CITA { get; set; }
        public int FL_DURACION { get; set; }
        public Nullable<int> FL_ESTATUS { get; set; }
        public string FL_ACUSE { get; set; }
        public byte[] FL_ARCHIVO { get; set; }
        public string FL_GUID { get; set; }
        public string FL_MYME { get; set; }
        public string FL_REQUERIMIENTO { get; set; }
        public string FL_URL { get; set; }
        public string FL_GUID_SERVICIO { get; set; }
        public Nullable<int> FL_DIAS { get; set; }
        public string FL_NOMBRE_LARGO { get; set; }
        public string FL_TRAMITE_RELACIONADO { get; set; }
        public string FL_SISTEMA { get; set; }
        public Nullable<long> FL_ORDEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DOCUMENTOS> TB_DOCUMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DOCUMENTOS_TRAMITES> TB_DOCUMENTOS_TRAMITES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MISDOCUMENTOS> TB_MISDOCUMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TRAMITES_TB_CLASIFICACION> TB_TRAMITES_TB_CLASIFICACION { get; set; }
    }
}
