//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TRAMITES_TB_CLASIFICACION
    {
        public long PK_TRAMITE_CLASIFICACION { get; set; }
        public Nullable<long> FK_CLASIFICACION { get; set; }
        public Nullable<long> FK_TRAMITE { get; set; }
        public Nullable<long> FK_PADRE { get; set; }
    
        public virtual TB_CLASIFICACION TB_CLASIFICACION { get; set; }
        public virtual TB_CLASIFICACION TB_CLASIFICACION1 { get; set; }
        public virtual TB_TRAMITES TB_TRAMITES { get; set; }
    }
}
