//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER_TB_TRAMITES
    {
        public long PK_USER_TRAMITE { get; set; }
        public Nullable<long> FK_USER { get; set; }
        public Nullable<long> FK_TRAMITE { get; set; }
    }
}
