//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_USERS()
        {
            this.TB_DIRECCIONES = new HashSet<TB_DIRECCIONES>();
            this.TB_DOCUMENTOS = new HashSet<TB_DOCUMENTOS>();
            this.TB_LOG = new HashSet<TB_LOG>();
            this.TB_MISDOCUMENTOS = new HashSet<TB_MISDOCUMENTOS>();
        }
    
        public long PK_USER { get; set; }
        public string FL_NOMBRE { get; set; }
        public string FL_EMAIL { get; set; }
        public string FL_PASSWORD { get; set; }
        public Nullable<int> FL_ESTATUS { get; set; }
        public string FL_RFC { get; set; }
        public string FL_CURP { get; set; }
        public Nullable<System.DateTime> FL_FECHA { get; set; }
        public Nullable<int> FL_PERFIL { get; set; }
        public Nullable<long> FK_INSTITUCION { get; set; }
        public string FL_APELLIDO_P { get; set; }
        public string FL_APELLIDO_M { get; set; }
        public string FL_GUID { get; set; }
        public string FL_TELEFONO_O { get; set; }
        public string FL_TELEFONO_P { get; set; }
        public string FL_TEL_CEL { get; set; }
        public string FL_CALLE_F { get; set; }
        public string FL_NUM_I_F { get; set; }
        public string FL_NUMERO_E_F { get; set; }
        public string FL_COLONIA_F { get; set; }
        public string FL_POBLACION_F { get; set; }
        public string FL_ESTADO_F { get; set; }
        public string FL_CP_F { get; set; }
        public string FL_CALLE_P { get; set; }
        public string FL_NUM_E_P { get; set; }
        public string FL_NUMERO_I_P { get; set; }
        public string FL_COLONIA_P { get; set; }
        public string FL_ESTADO_P { get; set; }
        public string FL_CP_P { get; set; }
        public string FL_POBLACION_P { get; set; }
        public Nullable<bool> FL_TERMINOS { get; set; }
        public Nullable<System.DateTime> FL_FECHA_NACIMIENTO { get; set; }
        public string FL_NACIONALIDAD { get; set; }
        public string FL_LUGAR_NACIMEINTO { get; set; }
        public string FL_ESCOLARIDAD { get; set; }
        public string FL_SESSION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DIRECCIONES> TB_DIRECCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DOCUMENTOS> TB_DOCUMENTOS { get; set; }
        public virtual TB_INSTITUCIONES TB_INSTITUCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LOG> TB_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MISDOCUMENTOS> TB_MISDOCUMENTOS { get; set; }
    }
}
